GET https://localhost:7267/trucks

###

GET https://localhost:7267/trucks/9

###

POST https://localhost:7267/trucks
Content-Type:	application/json

{
	"Model": "Test",
	"BrandId": 1,
	"maxSpeed": 120,
	"maxLiftingCapacity": 40,
	"Price": 10000,
	"ReleaseDate": "1999-05-08"
}

###

PUT https://localhost:7267/trucks/25
Content-Type: application/json

{
	 "Model": "MemeModel2",
   "BrandId": 5,
	 "maxSpeed": 120,
	 "maxLiftingCapacity": 40,
	 "Price": 15000,
	 "ReleaseDate": "1999-05-08"
}

###

DELETE https://localhost:7267/trucks/24