GET https://localhost:7267/trucks

###

GET https://localhost:7267/trucks/12

###

POST https://localhost:7267/trucks
Content-Type:	application/json

{
	"Model": "NEwTruck",
	"BrandId": 1,
	"maxSpeed": 120,
	"maxLiftingCapacity": 40,
	"Price": 9000,
	"ReleaseDate": "1999-05-08"
}

###

PUT https://localhost:7267/trucks/21
Content-Type: application/json

{
	 "Model": "MemeModel2",
   "BrandId": 5,
	 "maxSpeed": 120,
	 "maxLiftingCapacity": 40,
	 "Price": 9000,
	 "ReleaseDate": "1999-05-08"
}

###

DELETE https://localhost:7267/trucks/21